### PR TITLE
Controllers

### PR DESCRIPTION
**Pull request by peterdolan**
What: Added controllers/tests for controllers.
Why: Full api functionality now!

Meta: This includes changes already staged for change in validator. If this is a problem, I can change it -- other wise, diff is  [here](https://github.com/peterdolan/sfmovies/compare/validator...controllers)

### CODE REVIEW

**Comment by charlesbjohnson** [comment]
@peterdolan I think you need to force push the changes that we rebased through together on Friday. Otherwise it looks like this branch is based off of the old validators branch (note how this branch includes a validator commit that is different from the one in #3,  67da27d here vs 2d60536 there).

**Comment by peterdolan** [comment]
@charlesbjohnson You're right, not sure how that happened... Seems to be fixed now, both are based on the same commit now.

**Comment by charlesbjohnson** [comment]
Ahhh, sorry. This should be against `master`, not `validator`. I think you'll need to close and re-open another PR to change that 😦

Also, it still looks like the validator changes got pulled in, but they got pulled into your controller commits. We should still keep these separate, otherwise we'll run into merge conflicts once #3 gets merged. LMK if you have any questions.

**Comment by peterdolan** [comment]
Got it, that's annoying but oh well! I'll start doing it now

**Pull request closed without merging**
